// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJog37hNqVRO71sr1VSdVj4NAmsxVmQYg',
    appId: '1:873506873374:web:3d6b5e1022911dbb2d4e0f',
    messagingSenderId: '873506873374',
    projectId: 'green-field-5618b',
    authDomain: 'green-field-5618b.firebaseapp.com',
    storageBucket: 'green-field-5618b.firebasestorage.app',
    measurementId: 'G-JN6SPFDGX1',
    iosClientId:
        '873506873374-p1lvhgu83mu7qm9onobu1jbnroth83kc.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdqlRJhwqCkps0kdTMxLhUT01HiYcBhV8',
    appId: '1:873506873374:android:ff97969d6f48c82e2d4e0f',
    messagingSenderId: '873506873374',
    projectId: 'green-field-5618b',
    storageBucket: 'green-field-5618b.firebasestorage.app',
  );
}
